"use client";

import Image from "next/image";
import {
  FolderGit2,
  LayoutGrid,
  MessageSquare,
  Sparkles,
  SquareTerminal,
} from "lucide-react";
import { useEffect, useState } from "react";
import { useViewportActivity } from "@/components/use-viewport-activity";
import { CANVAS_CONCEPTS } from "./data";

function PlanArtifact() {
  return (
    <div className="artifact artifact--plan">
      <div className="artifact__bar">
        <Sparkles size={11} />
        <span>Generated by Stella</span>
      </div>
      <div className="artifact__heading">Weekend Trip — San Diego</div>
      <div className="artifact__plan-grid">
        <div className="artifact-card">
          <div className="artifact-card__head artifact-card__head--blue">✈ Flight</div>
          <strong>SFO → SAN</strong>
          <span>Fri Mar 28 · 1h 22m direct</span>
          <em>$124 round trip</em>
        </div>
        <div className="artifact-card">
          <div className="artifact-card__head artifact-card__head--amber">★ Hotel</div>
          <strong>Hotel del Coronado</strong>
          <span>4.6 rating · Beachfront</span>
          <em>$189 / night</em>
        </div>
        <div className="artifact-card">
          <div className="artifact-card__head artifact-card__head--rose">♦ Dining</div>
          <strong>Top 5 picks saved</strong>
          <span>Seafood · Mexican · Italian</span>
          <em>Outdoor seating available</em>
        </div>
        <div className="artifact-card artifact-card--wide">
          <div className="artifact-card__head artifact-card__head--green">◎ Budget breakdown</div>
          <div className="artifact-bars">
            <div className="artifact-bar">
              <span>Flights</span>
              <div className="artifact-bar__track"><div style={{ width: "24%" }} /></div>
              <span>$124</span>
            </div>
            <div className="artifact-bar">
              <span>Hotel</span>
              <div className="artifact-bar__track"><div className="artifact-bar__fill--amber" style={{ width: "55%" }} /></div>
              <span>$378</span>
            </div>
            <div className="artifact-bar">
              <span>Food &amp; misc</span>
              <div className="artifact-bar__track"><div className="artifact-bar__fill--green" style={{ width: "22%" }} /></div>
              <span>$150</span>
            </div>
          </div>
          <strong className="artifact-card__total">Estimated total: ~$652</strong>
        </div>
      </div>
    </div>
  );
}

function CompareArtifact() {
  return (
    <div className="artifact artifact--compare">
      <div className="artifact__bar">
        <Sparkles size={11} />
        <span>Generated by Stella</span>
      </div>
      <div className="artifact__heading">Laptop Comparison</div>
      <div className="artifact-table">
        <div className="artifact-table__head">
          <span />
          <span>MacBook Air M3</span>
          <span className="artifact-table__pick">Dell XPS 14 ★</span>
          <span>ThinkPad X1</span>
        </div>
        <div className="artifact-table__row">
          <span>Price</span>
          <span>$1,099</span>
          <span>$1,199</span>
          <span>$1,349</span>
        </div>
        <div className="artifact-table__row">
          <span>Display</span>
          <span>13.6&quot; Retina</span>
          <span>14.5&quot; OLED</span>
          <span>14&quot; IPS 2.8K</span>
        </div>
        <div className="artifact-table__row">
          <span>Battery</span>
          <span>18 hr</span>
          <span>13 hr</span>
          <span>15 hr</span>
        </div>
        <div className="artifact-table__row">
          <span>Weight</span>
          <span>2.7 lb</span>
          <span>3.8 lb</span>
          <span>3.0 lb</span>
        </div>
        <div className="artifact-table__row">
          <span>Best for</span>
          <span>Portability</span>
          <span>Creative work</span>
          <span>Business</span>
        </div>
      </div>
      <div className="artifact__verdict">
        <Sparkles size={11} />
        Best match for your needs: <strong>Dell XPS 14</strong> — OLED display + strong performance
      </div>
    </div>
  );
}

function ReportArtifact() {
  return (
    <div className="artifact artifact--report">
      <div className="artifact__bar">
        <Sparkles size={11} />
        <span>Generated by Stella</span>
      </div>
      <div className="artifact__heading">Q1 Performance Summary</div>
      <div className="artifact-metrics">
        <div className="artifact-metric">
          <span className="artifact-metric__value artifact-metric__value--green">+23%</span>
          <span>Revenue growth</span>
        </div>
        <div className="artifact-metric">
          <span className="artifact-metric__value artifact-metric__value--blue">1,847</span>
          <span>New customers</span>
        </div>
        <div className="artifact-metric">
          <span className="artifact-metric__value artifact-metric__value--amber">94.2%</span>
          <span>Retention rate</span>
        </div>
      </div>
      <div className="artifact-mini-table">
        <div className="artifact-mini-table__head">
          <span>Channel</span>
          <span>Revenue</span>
          <span>Growth</span>
        </div>
        <div className="artifact-mini-table__row">
          <span>Direct</span>
          <span>$48.2K</span>
          <span className="artifact-mini-table__up">↑ 31%</span>
        </div>
        <div className="artifact-mini-table__row">
          <span>Referral</span>
          <span>$22.8K</span>
          <span className="artifact-mini-table__up">↑ 18%</span>
        </div>
        <div className="artifact-mini-table__row">
          <span>Organic</span>
          <span>$16.4K</span>
          <span className="artifact-mini-table__up">↑ 12%</span>
        </div>
      </div>
      <div className="artifact-actions">
        <strong>Suggested next steps</strong>
        <div className="artifact-action">
          <span className="artifact-action__check">✓</span>
          Double down on direct sales — highest ROI channel
        </div>
        <div className="artifact-action">
          <span className="artifact-action__dot" />
          Launch referral incentive program
        </div>
        <div className="artifact-action">
          <span className="artifact-action__dot" />
          Review organic SEO strategy for Q2
        </div>
      </div>
    </div>
  );
}

const ARTIFACT_MAP: Record<string, React.FC> = {
  launch: PlanArtifact,
  agents: CompareArtifact,
  timeline: ReportArtifact,
};

export function CanvasShowcase() {
  const [conceptIndex, setConceptIndex] = useState(0);
  const { ref, isActive } = useViewportActivity<HTMLDivElement>({
    rootMargin: "240px 0px",
  });

  useEffect(() => {
    if (!isActive) return;

    const timer = window.setInterval(() => {
      setConceptIndex((current) => (current + 1) % CANVAS_CONCEPTS.length);
    }, 5500);
    return () => window.clearInterval(timer);
  }, [isActive]);

  const activeConcept = CANVAS_CONCEPTS[conceptIndex];
  const ArtifactComponent = ARTIFACT_MAP[activeConcept.id] ?? PlanArtifact;

  return (
    <div ref={ref} className="canvas-showcase">
      <div className="canvas-showcase__meta">
        <div className="demo-eyebrow">Full shell</div>
        <h3>{activeConcept.title}</h3>
        <p>{activeConcept.blurb}</p>

        <div className="canvas-showcase__tabs">
          {CANVAS_CONCEPTS.map((concept, index) => (
            <button
              key={concept.id}
              type="button"
              className="canvas-showcase__tab"
              data-active={conceptIndex === index || undefined}
              onClick={() => setConceptIndex(index)}
            >
              {concept.label}
            </button>
          ))}
        </div>
      </div>

      <div className="shell-preview">
        <div className="shell-preview__titlebar">
          <div className="shell-preview__traffic">
            <span />
            <span />
            <span />
          </div>
        </div>

        <div className="shell-preview__body">
          <aside className="shell-sidebar">
            <div className="shell-sidebar__brand">
              <Image src="/stella-logo.svg" alt="" width={20} height={20} />
              <strong>Stella</strong>
            </div>

            <nav className="shell-sidebar__nav" aria-label="Shell navigation">
              <button type="button" data-active>
                <LayoutGrid size={16} />
                <span>Canvas</span>
              </button>
              <button type="button">
                <MessageSquare size={16} />
                <span>Threads</span>
              </button>
              <button type="button">
                <SquareTerminal size={16} />
                <span>Tasks</span>
              </button>
              <button type="button">
                <FolderGit2 size={16} />
                <span>Projects</span>
              </button>
            </nav>
          </aside>

          <div className="shell-workspace">
            <div className="shell-workspace__canvas">
              <ArtifactComponent key={activeConcept.id} />
            </div>
          </div>

          <aside className="shell-activity">
            <div className="shell-activity__header">
              <strong>Activity</strong>
              <span>{activeConcept.activity.length} items</span>
            </div>

            <div className="shell-activity__list">
              {activeConcept.activity.map((entry) => (
                <article key={entry.id} className="shell-activity__item">
                  <strong className="shell-activity__name">{entry.name}</strong>
                  <em>{entry.meta}</em>
                  <p>{entry.preview}</p>
                </article>
              ))}
            </div>
          </aside>
        </div>
      </div>
    </div>
  );
}
