import Image from "next/image";
import type { CSSProperties } from "react";
import styles from "./home-canvas-demos.module.css";

const SURFACES = [
  {
    label: "Trip planner",
    src: "/app-mocks/travel.jpg",
    alt: "Trip planner interface generated by Stella.",
    width: 2048,
    height: 1152,
  },
  {
    label: "Creative canvas",
    src: "/app-mocks/canvas.jpg",
    alt: "Creative canvas interface generated by Stella.",
    width: 2048,
    height: 1152,
  },
  {
    label: "Studio",
    src: "/app-mocks/studio.jpg",
    alt: "Music studio interface generated by Stella.",
    width: 2048,
    height: 1152,
  },
  {
    label: "Dashboard",
    src: "/app-mocks/dashboard.jpg",
    alt: "Dashboard interface generated by Stella.",
    width: 2048,
    height: 1152,
  },
  {
    label: "Ops terminal",
    src: "/app-mocks/terminal.jpg",
    alt: "Terminal interface generated by Stella.",
    width: 2048,
    height: 1152,
  },
  {
    label: "Live streaming",
    src: "/app-mocks/streaming.jpg",
    alt: "Streaming interface generated by Stella.",
    width: 2048,
    height: 1152,
  },
];

export function HomeCanvasDemos() {
  return (
    <section
      className={`grid-shell section-border home-atlas-section ${styles.section}`}
      data-reveal
    >
      <div
        className="home-atlas-heading"
        data-reveal-child
        style={{ ["--reveal-index" as string]: 0 }}
      >
        <h2>Make Stella yours.</h2>
      </div>

      <div className="home-atlas-scene">
        <div
          className={`home-atlas-media home-atlas-media--left ${styles.media}`}
          data-reveal-child
          style={{ ["--reveal-index" as string]: 1 }}
        >
          <div
            className={styles.carousel}
            aria-label="Examples of Stella app surfaces"
          >
            {SURFACES.map((surface, index) => (
              <figure
                className={styles.slide}
                key={surface.src}
                style={{ "--delay": `${index * 4}s` } as CSSProperties}
              >
                <Image
                  src={surface.src}
                  alt={surface.alt}
                  width={surface.width}
                  height={surface.height}
                  loading={index === 0 ? "eager" : "lazy"}
                  quality={82}
                  sizes="(max-width: 860px) 92vw, 44rem"
                  className={styles.image}
                />
              </figure>
            ))}
          </div>

          <div className={styles.rail} aria-hidden="true">
            {SURFACES.map((surface, index) => (
              <span
                key={surface.label}
                style={{ "--delay": `${index * 4}s` } as CSSProperties}
              />
            ))}
          </div>
        </div>

        <div
          className="home-atlas-copy home-atlas-copy--right"
          data-reveal-child
          style={{ ["--reveal-index" as string]: 2 }}
        >
          <span className="home-atlas-kicker">Surfaces</span>
          <p>
            Stella turns requests into visible work: custom interfaces,
            dashboards, planners, studios, and operating surfaces that keep
            context attached to the conversation.
          </p>
        </div>
      </div>
    </section>
  );
}
