import Image from "next/image";
import styles from "./home-canvas-demos.module.css";

const SURFACES = [
  {
    label: "Trip planner",
    title: "A request becomes a working itinerary.",
    src: "/app-mocks/travel.jpg",
    alt: "Trip planner interface generated by Stella.",
    width: 2048,
    height: 1152,
    className: styles.primaryCard,
  },
  {
    label: "Creative canvas",
    title: "A blank ask turns into a visual workspace.",
    src: "/app-mocks/canvas.jpg",
    alt: "Creative canvas interface generated by Stella.",
    width: 2048,
    height: 1152,
    className: styles.wideCard,
  },
  {
    label: "Studio",
    title: "A job gets its own controls.",
    src: "/app-mocks/studio.jpg",
    alt: "Music studio interface generated by Stella.",
    width: 2048,
    height: 1152,
    className: styles.tileCard,
  },
  {
    label: "Dashboard",
    title: "A plan becomes something you can track.",
    src: "/app-mocks/dashboard.jpg",
    alt: "Dashboard interface generated by Stella.",
    width: 2048,
    height: 1152,
    className: styles.tileCard,
  },
  {
    label: "Ops terminal",
    title: "Power work can stay dense.",
    src: "/app-mocks/terminal.jpg",
    alt: "Terminal interface generated by Stella.",
    width: 2048,
    height: 1152,
    className: styles.overlapCard,
  },
  {
    label: "Fitness coach",
    title: "A routine becomes a training surface.",
    src: "/app-mocks/fitness.jpg",
    alt: "Fitness coach interface generated by Stella.",
    width: 687,
    height: 1442,
    className: styles.floatPortraitCard,
  },
  {
    label: "Calm space",
    title: "The interface can narrow to the moment.",
    src: "/app-mocks/breathe.jpg",
    alt: "Calm breathing interface generated by Stella.",
    width: 560,
    height: 1365,
    className: styles.portraitCard,
  },
];

export function HomeCanvasDemos() {
  return (
    <section className={`grid-shell section-border ${styles.section}`}>
      <div className={styles.header}>
        <span className={styles.index}>1.0</span>
        <div>
          <span className={styles.eyebrow}>Surfaces</span>
          <h2>Make Stella yours.</h2>
          <p>
            Stella turns requests into visible work: custom interfaces,
            dashboards, planners, studios, and operating surfaces that keep
            context attached to the conversation.
          </p>
        </div>
      </div>

      <div className={styles.mosaic}>
        {SURFACES.map((surface) => (
          <article className={`${styles.surfaceCard} ${surface.className}`} key={surface.src}>
            <figure className={styles.frame}>
              <Image
                src={surface.src}
                alt={surface.alt}
                width={surface.width}
                height={surface.height}
                loading="eager"
                unoptimized
                sizes="(max-width: 820px) 92vw, 42rem"
                className={styles.image}
              />
            </figure>
            <div className={styles.surfaceCopy}>
              <span>{surface.label}</span>
              <strong>{surface.title}</strong>
            </div>
          </article>
        ))}
      </div>
    </section>
  );
}
